QSimpleUpdater: Downloader Class Reference
Downloader Class Reference
Implements an integrated file downloader with a nice UI.
#include <Downloader.h>
Public Slots
void startDownload (const QUrl &url)
void setUseCustomInstallProcedures (const bool &custom)
Signals
void downloadFinished (const QString &url, const QString &filepath)
Public Member Functions
Downloader (QWidget *parent=0)
bool useCustomInstallProcedures () const
Detailed Description
Implements an integrated file downloader with a nice UI.
Member Function Documentation
void Downloader::setUseCustomInstallProcedures (const bool & custom) slot
If the custom parameter is set to true, then the Downloader will not attempt to open the downloaded file.
Use the signals fired by the QSimpleUpdater to implement your own install procedures.
Referenced by Updater::setUseCustomInstallProcedures().
void Downloader::startDownload (const QUrl & url) slot
Begins downloading the file at the given url
References useCustomInstallProcedures().
Referenced by Updater::setUseCustomInstallProcedures().
bool Downloader::useCustomInstallProcedures () const
Returns true if the updater shall not intervene when the download has finished (you can use the QSimpleUpdater signals to know when the download is completed).
Referenced by startDownload(), and Updater::useCustomInstallProcedures().
The documentation for this class was generated from the following files:
Downloader.h
Downloader.cpp